# Generated by Django 4.0 on 2022-01-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('status', models.BooleanField()),
                ('time', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('date_submit', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
