# Generated by Django 4.0 on 2022-01-03 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programming_language', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('exercise', '0001_initial'),
        ('code_submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programming_language.programminglanguage'),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
