# Generated by Django 4.0 on 2022-02-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_submission', '0004_alter_codesubmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='sys_out',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
