# Generated by Django 4.0 on 2022-02-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_submission', '0006_rename_sys_out_codesubmission_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesubmission',
            name='status',
            field=models.CharField(choices=[(200, 'OK'), (201, 'ACCEPTED'), (400, 'WRONG ANSWER'), (401, 'COMPILATION ERROR'), (402, 'RUNTIME ERROR'), (403, 'INVALID FILE'), (404, 'FILE NOT FOUND'), (408, 'TIME LIMIT EXCEEDE')], max_length=40),
        ),
    ]
