# Generated by Django 4.0 on 2022-02-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_submission', '0007_alter_codesubmission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesubmission',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('ACCEPTED', 'ACCEPTED'), ('WRONG ANSWER', 'WRONG ANSWER'), ('COMPILATION ERROR', 'COMPILATION ERROR'), ('RUNTIME ERROR', 'RUNTIME ERROR'), ('INVALID FILE', 'INVALID FILE'), ('FILE NOT FOUND', 'FILE NOT FOUND'), ('TIME LIMIT EXCEEDED', 'TIME LIMIT EXCEEDED')], max_length=40),
        ),
    ]
