# Generated by Django 4.0 on 2022-03-18 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_contest_description'),
        ('code_submission', '0008_alter_codesubmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='id_contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.contest'),
        ),
    ]
