# Generated by Django 4.0 on 2022-03-18 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_submission', '0009_codesubmission_id_contest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codesubmission',
            old_name='id_contest',
            new_name='contest',
        ),
    ]
