# Generated by Django 4.0 on 2022-03-19 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('code_submission', '0010_rename_id_contest_codesubmission_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.class'),
        ),
    ]
