# Generated by Django 4.0 on 2022-03-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='data_end',
            new_name='date_end',
        ),
        migrations.AddField(
            model_name='contest',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
