# Generated by Django 4.0 on 2022-03-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_rename_data_end_contest_date_end_contest_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
