# Generated by Django 4.0 on 2022-03-16 17:05

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_alter_contest_name_alter_contest_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='description',
            field=django_editorjs_fields.fields.EditorJsTextField(default='Hello'),
            preserve_default=False,
        ),
    ]
