# Generated by Django 4.0 on 2022-01-03 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programming_language', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('level', models.TextField()),
                ('question', models.TextField()),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('test_case', models.TextField()),
                ('output_test_case', models.TextField()),
                ('memory_limits', models.IntegerField()),
                ('time_limits', models.IntegerField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', related_query_name='post', to='auth.user')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programming_language.programminglanguage')),
            ],
        ),
    ]
