# Generated by Django 4.0 on 2022-02-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming_language', '0001_initial'),
        ('exercise', '0006_alter_exercise_slug_alter_exercise_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='language',
        ),
        migrations.AddField(
            model_name='exercise',
            name='language',
            field=models.ManyToManyField(to='programming_language.ProgrammingLanguage'),
        ),
    ]
