# Generated by Django 4.0 on 2022-02-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_remove_exercise_language_exercise_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='test_case',
            field=models.TextField(blank=True, null=True),
        ),
    ]
