# Generated by Django 4.0 on 2022-02-19 09:12

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_alter_exercise_test_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='input',
            field=django_editorjs_fields.fields.EditorJsTextField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='output',
            field=django_editorjs_fields.fields.EditorJsTextField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='question',
            field=django_editorjs_fields.fields.EditorJsTextField(),
        ),
    ]
