# Generated by Django 4.0 on 2022-02-26 09:23

from django.db import migrations, models
import exercise.models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0009_alter_exercise_input_alter_exercise_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='test_input',
            field=models.FileField(blank=True, null=True, upload_to=exercise.models.change_name_file_input),
        ),
        migrations.AddField(
            model_name='exercise',
            name='test_output',
            field=models.FileField(blank=True, null=True, upload_to=exercise.models.change_name_file_output),
        ),
    ]
