# Generated by Django 4.0 on 2022-02-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programming_language', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programminglanguage',
            old_name='command',
            new_name='ext',
        ),
    ]
