# Generated by Django 4.0 on 2022-02-09 11:23

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_editorjs',
            field=django_editorjs_fields.fields.EditorJsJSONField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_editorjs_text',
            field=django_editorjs_fields.fields.EditorJsTextField(default=' '),
            preserve_default=False,
        ),
    ]
