# Generated by Django 4.0 on 2022-02-09 11:34

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_lesson_content_editorjs_lesson_content_editorjs_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content_editorjs',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='content_editorjs_text',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=django_editorjs_fields.fields.EditorJsTextField(),
        ),
    ]
