# Generated by Django 4.0 on 2022-02-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_remove_lesson_content_editorjs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='content',
            new_name='content_editorjs_text',
        ),
    ]
