# Generated by Django 4.0 on 2022-02-09 11:36

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_rename_content_lesson_content_editorjs_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_editorjs',
            field=django_editorjs_fields.fields.EditorJsJSONField(default=' '),
            preserve_default=False,
        ),
    ]
