# Generated by Django 4.0 on 2022-02-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_remove_lesson_content_editorjs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='published_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
