# Generated by Django 4.0 on 2022-02-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0008_alter_lesson_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='slug',
            field=models.SlugField(blank=True, default='none', null=True),
        ),
    ]
