# Generated by Django 4.0 on 2022-02-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0009_subjects_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
