# Generated by Django 4.0 on 2022-03-02 16:10

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0010_alter_subjects_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_text',
            field=django_editorjs_fields.fields.EditorJsJSONField(default=' '),
            preserve_default=False,
        ),
    ]
