# Generated by Django 4.0 on 2022-03-02 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0011_lesson_content_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content_text',
        ),
    ]
