# Generated by Django 4.0 on 2022-03-19 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem_class',
            name='class_obj',
        ),
        migrations.RemoveField(
            model_name='problem_class',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='student_class',
            name='class_obj',
        ),
        migrations.RemoveField(
            model_name='student_class',
            name='student',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Problem_Class',
        ),
        migrations.DeleteModel(
            name='Student_Class',
        ),
    ]
